import pymysql.cursors
import os
from dotenv import load_dotenv

if __name__ == "__main__":
    load_dotenv('.env')
    # Connect to the database
    connection = pymysql.connect(host=os.getenv('HOST'),
                                 user=os.getenv('USER'),
                                 password=os.getenv('PASSWORD'),
                                 database=os.getenv('DATABASE'),
                                 cursorclass=pymysql.cursors.DictCursor)

    with connection:
        with connection.cursor() as cursor:
            # sql = "SELECT `id`, `password` FROM `users` WHERE `email`=%s"
            cursor.execute('DROP TABLE IF EXISTS book;')
            # cursor.execute('DROP TABLE IF EXISTS api_key;')

            # Create tables
            sql = 'CREATE TABLE `book` (' \
                  '`id` INT AUTO_INCREMENT PRIMARY KEY, ' \
                  '`cover_url` VARCHAR(255),' \
                  '`title` VARCHAR(255) NOT NULL, ' \
                  '`author` VARCHAR(255) NOT NULL, ' \
                  '`publication_year` INT NOT NULL, ' \
                  '`main_genre` VARCHAR(255) NOT NULL,' \
                  '`description` TEXT NOT NULL, ' \
                  '`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP);'
            cursor.execute(sql)

            sql = 'CREATE TABLE IF NOT EXISTS`api_key` (' \
                  '`id_api` INT AUTO_INCREMENT PRIMARY KEY,' \
                  '`email` VARCHAR(255) NOT NULL UNIQUE ,' \
                  '`api_key` VARCHAR(64) NOT NULL,' \
                  '`requests_count` INT,' \
                  '`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP);'
            # cursor.execute(sql)

            # Insert data
            default_cover = os.getenv('DEFAULT_COVER_IMG')
            sql = "INSERT INTO `book`(`cover_url`, `title`, `author`, `publication_year`, `main_genre`, " \
                  "`description`) VALUES " \
                  f"('https://firebasestorage.googleapis.com/v0/b/paw-1-5a796.appspot.com/o/images%2F1.jpg?alt=media&token=fa3b8a57-38c3-4c15-8f31-831235c5903a', 'Mroki łowisk', 'Anna Kasiuk', 2016, 'Romance', 'Nie wszystkie rany zaleczy czas i miłość.\n\nPrzekonała się o tym Majka, która uparcie próbuje ułożyć sobie nowe życie w zakątku malowniczych Łowisk położonych na Mazurach. Wrodzona determinacja młodej pani psycholog może nie wystarczyć, by przyciągnąć upragnione szczęście, gdy w grę wchodzą zatargi z nadnaturalnymi mocami oraz powiązana z nimi przedwieczna tajemnica.')," \
                  f"('{default_cover}', 'Murder in the Family', 'Cara Hunter', 2023, 'Crime', 'From the Sunday Times Bestselling author of CLOSE TO HOME comes a brilliant standalone thriller you’ll never forget ‘Original, inventive and totally 21st Century … The twists are magnificent! It really is an equal triumph of style and content. Just brilliant!” Janice Hallett, author of The Appeal ‘It is the most addictive book you will read all year … Uniquely told and simply bloody brilliant.’ John Marrs ‘I adored it! So brilliantly put together, so full of twists and revelations … truly a cracker of a book.’ JP Delaney IT WAS A CASE THAT GRIPPED THE NATION LUKE RYDER’S MURDER HAS NEVER BEEN SOLVED In December 2003, Luke Ryder was found dead in the garden of the family home in London, leaving behind a wealthy older widow and three stepchildren. Nobody saw anything. Now, secrets will be revealed – live on camera. Years later a group of experts re-examine the evidence on Infamous, a true-crime show – with shocking results. Does the team know more than they’ve been letting on? Or does the truth lie closer to home? Can you solve the case before they do? The truth will blow your mind.')," \
                  f"('https://firebasestorage.googleapis.com/v0/b/paw-1-5a796.appspot.com/o/images%2F3.jpg?alt=media&token=42809dd1-8993-4c7c-931d-474efc0964b6', 'Bezsenność', 'Stephen King', 2006, 'Horror', 'Ralph Roberts cierpi na bezsenność. Im krócej sypia, tym dziwniej postrzega świat i ludzi – wydaje mu się, że zaczyna widzieć ich „aury”, a także tajemnicze istoty towarzyszące zgonom jego znajomych i przyjaciół. Derry (miasteczko, w którym mieszka) jest podzielone w związku z powstaniem szpitala, „centrum opieki”, w którym dokonuje się m.in. zabiegów aborcji. Niepokoje inspirują zrzeszeni w „ProLife” obrońcy życia nienarodzonych dzieci. Na czele ruchu stoi człowiek obłąkany, sadysta skazany za znęcanie się nad własną rodziną. Planuje on zamach na centrum i zgładzenie przebywających tam ludzi. Jest wśród nich chłopiec, w którego rękach spoczywa los wszechświata. Tylko Ralph, dzięki swoim niezwykłym zdolnościom, postrzegania może go ocalić...')," \
                  f"('https://firebasestorage.googleapis.com/v0/b/paw-1-5a796.appspot.com/o/images%2F4.jpg?alt=media&token=065afd04-f89b-4b4f-ac09-adf39d8fc3ce', 'Tajne państwo. Opowieść o polskim Podziemiu', 'Jan Karski', 2023, 'History', 'Nikt nie wiedział o Polskim Państwie Podziemnym tyle co on. Mimo śmiertelnego zagrożenia kilka razy przemierzył Europę jako jego tajny emisariusz. Wpadł tylko raz. Torturowany przez Niemców, bojąc się, że zdradzi, targnął się na swoje życie. Ryzykując rozstrzelanie, przedarł się do warszawskiego getta i do obozu w Izbicy. Złożył przywódcom aliantów wstrząsający raport o nazistowskich zbrodniach. On pierwszy usiłował obudzić sumienie świata i zatrzymać Holokaust. Nazywał się Karski. Jan Karski – najsłynniejszy kurier Polski Walczącej. „Tajne państwo” ukazało się w Ameryce w 1944 roku i natychmiast stało się bestsellerem. W siedemdziesiątą rocznicę premiery legendarna książka ukazuje się w nowym tłumaczeniu. Powinien ją mieć na półce każdy polski patriota.')," \
                  f"('https://firebasestorage.googleapis.com/v0/b/paw-1-5a796.appspot.com/o/images%2F5.jpg?alt=media&token=689b13f6-0b02-438c-ac8e-3761711e19d3', 'Złodziej kanapek', 'Andrea Camilleri', 2003, 'Crime', 'Nowe wydanie trzeciego tomu bestsellerowej serii kryminałów! Komisarz Montalbano - człowiek o nastrojach zmiennych jak sycylijska aura i niezrównany smakosz - musi rozwiązać sprawę tunezyjskiego rybaka, zatrudnionego na włoskim kutrze i zabitego od strzału oddanego z tunezyjskiej łodzi patrolowej. Jednocześnie w Vigacie ofiarą morderstwa pada właściciel firmy handlowej, Aurelio Lapecora. Wdowa rzuca oskarżenie na kochankę denata, piękną Tunezyjkę imieniem Karima. Okazuje się, że przedsiębiorcza emigrantka szczególnie upodobała sobie majętnych starszych panów, którym świadczyła dość wymyślne usługi. Borykający się z bardzo trudnymi problemami osobistymi komisarz Montalbano dojdzie z czasem do wniosku, że pochodzenie osób uwikłanych w te dwie, zdawałoby się, zupełnie niepowiązane ze sobą sprawy będzie mieć kluczowe znaczenie dla rozwiązania jednej groźnej zagadki.')," \
                  f"('https://firebasestorage.googleapis.com/v0/b/paw-1-5a796.appspot.com/o/images%2F6.jpg?alt=media&token=b54db41c-8481-41e8-b6e8-ace0f045b077', 'I Want Your Life', 'Gabriela Rygiel', 2023, 'Romance', 'Emma Douglas studiuje dziennikarstwo na uniwersytecie w Pensylwanii. Podobnie jak inni studenci z uwagą śledzi artykuły ukazujące się w plotkarskiej gazecie uczelnianej „Last but not Least”. W zasadzie to pismo jest prawdziwą biblią dla studentów. Można dowiedzieć się z niego wielu ciekawych rzeczy na temat różnych studentów, jak również ocenić, czy ma się szansę u konkretnego chłopaka. Szczególną gwiazdą na kampusie jest Luke Henderson, kapitan drużyny koszykarskiej. Emma od początku z uwagą obserwuje jego poczynania i nie potrafi zaprzeczyć, że chłopak podbił jej serce. Jednak dziewczyna ma bardzo niską samoocenę i dobrze wie, że nigdy nie miałaby szans u kogoś takiego jak Luke. Ale wkrótce poznaje go osobiście i zaczyna odkrywać, że za jego powszechnie znanym wizerunkiem kryje się ktoś zupełnie inny. Książka zawiera treści nieodpowiednie dla osób poniżej szesnastego roku życia.')," \
                  f"('https://firebasestorage.googleapis.com/v0/b/paw-1-5a796.appspot.com/o/images%2F7.jpg?alt=media&token=2abf1dcc-92db-4337-b0ba-81811dc6c05b', 'Czarna jaskółka', 'Liliana Więcek', 2023, 'Romance', 'Czwarty tom bestsellerowej serii mafijnej z zadziornymi góralkami! Monika Pociasková to góralka żyjąca pragnieniem zemsty. Zrobi wszystko, żeby poczuć jej słodki smak. Przed laty spotkało ją coś bardzo złego, a ten, który ponosi winę za jej krzywdę, z pewnością za to zapłaci. Na jej drodze staje mafioso Jack Adams. To wyjątkowo groźny mężczyzna. Monika bezceremonialnie wyrzuca go ze swojego hotelu, przeczuwając, z kim ma do czynienia. Teraz, po kilku miesiącach, Jack wraca w polskie góry, żeby pokazać kobiecie, że z kimś takim jak on się nie zadziera. Jednak Jack nie ma pojęcia, że Monika już czeka, aby wciągnąć go w bardzo niebezpieczną grę, w której stawką jest życie. Bo przecież, gdzie dwa diabły wrzucają do pieca… Tam będą królowały ogień, zniszczenie i śmierć… Książka zawiera treści nieodpowiednie dla osób poniżej osiemnastego roku życia.')," \
                  f"('https://firebasestorage.googleapis.com/v0/b/paw-1-5a796.appspot.com/o/images%2F8.jpg?alt=media&token=9d156c92-d845-4548-96f8-3517892121d3', 'Smak tabaki', 'Daria Kaszubowska', 2023, 'Romance', 'Jak pogodzić szaloną miłość z odpowiedzialnością za dzieci i rodzinę? Co wygra: rozsądek czy serce? Wanda, matka trójki dzieci, tkwiąca w niesatysfakcjonującym małżeństwie, i starszy od niej o szesnaście lat Leon, kaszubski działacz, człowiek nietuzinkowy, nawiązują gorący romans.')," \
                  f"('{default_cover}', 'Purpurowe łzy', 'Beata Majewska', 2023, 'Romance', 'LĘK PRZED STRATĄ BYWA TAK SAMO BOLESNY JAK STRATA… Nie wiadomo kiedy Alija z brzydkiego kaczątka zmieniła się w prawdziwą piękność. Wychowanka Karima Kasymowa spędza całe dnie w jego luksusowej willi jako pokojówka, ale przede wszystkim wierna przyjaciółka Fabiany, ukochanej Chana. Młoda muzułmanka coraz częściej odczuwa jednak samotność, a kiedy w rezydencji pojawia się nowy ogrodnik, przystojny Michał Chłodny, dociera do niej, że się zakochała i to z wzajemnością. Nie wie, że Michał skrywa mroczny sekret, który determinuje jego postępki. Tyko Radik, zastępca Karima, czuje niechęć do ogrodnika, ale nikt nie bierze na poważnie jego zastrzeżeń, a już na pewno nie zakochana po uszy dziewczyna. Niestety, oni wszyscy słono za to zapłacą. Alija i Fabiana padną ofiarą planów Polaka i trafią w sam środek piekła. Jaką rolę w dramacie odegra Ksenia, córka Dżamili? Kim naprawdę jest Michał Chłodny? I co sprawi, że Alija znajdzie się w miejscu, skąd nie ma żadnego wyjścia poza tym ostatecznym?')," \
                  f"('https://firebasestorage.googleapis.com/v0/b/paw-1-5a796.appspot.com/o/images%2F10.jpg?alt=media&token=d673e282-62e4-4298-9c73-15a803a5e56f', 'Dirty Girl', 'Meghan March', 2016, 'Science Fiction', 'Greer Karas, siostra Creightona Karasa, miliardera o paskudnej opinii, nigdy nie była miłą i grzeczną dziewczyną. Była za to harda, uparta i zadziorna, a do tego na tyle bystra, aby jako jedna z najlepszych studentek ukończyć studia prawnicze. Zwykle osiągała to, czego zapragnęła, chociaż czasami ponosiła porażki. Tak jak trzy lata temu, gdy czekała samotnie na szczycie Skały na ukochanego. A on nie przyszedł. Zniknął z jej życia bez słowa wyjaśnienia.\n\nCavanaugh Westman był wówczas zupełnie nieznany i niewiele znaczył. Ale w ciągu kolejnych lat wspiął się na szczyty sławy. Stał się najgorętszym aktorem Hollywood. Wciąż dotrzymywał danego sobie słowa, że będzie się trzymał z dala od Greer. Co być może nadal by mu się udawało, gdyby nie to, że dziewczynie pod wpływem alkoholu zdarzało się robić naprawdę głupie rzeczy. Tym razem było to opublikowanie sprośnego ogłoszenia w internecie. W dodatku pod własnym nazwiskiem! Cav mógł zareagować tylko w jeden sposób. Wsiąść do prywatnego odrzutowca i... zapukać do drzwi Greer.\n\nGdyby chodziło o miłą dziewczynę i fajnego faceta, byłoby o wiele łatwiej. Ona wiedziała, że go kocha, a on był zdeterminowany, by za wszelką cenę chronić ją przed wszystkim i wszystkimi — nawet przed nią samą. Tyle że Greer zawsze była niezależna i sama podejmowała decyzje. I nie mogła zapomnieć, że kiedyś Cav ją opuścił. Szybko zrozumiała, że nawet najlepszy seks nie zastąpi zaufania.\n\nTym bardziej że młodszą siostrą miliardera zawsze będą się interesować źli ludzie.\n\nPrawdziwe życie nie jest dla osób o słabych nerwach!');"
            cursor.execute(sql)

            # Save changes to the database
            connection.commit()

            # cursor.execute("SELECT * FROM book;")
            # result = cursor.fetchall()
            # print(result)
